uvmc.o_DEP_O = /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player/csrc/sysc/uvmc.o
$(uvmc.o_DEP_O):	FORCE
	$(ACTIVE) $(MDIR_csrc) (cd /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player; $(VCS_HOME)/bin/syscan  -sysc=231 -V -work DEFAULT -full64 -cc /usr/bin/gcc -cpp /usr/bin/g++ -tlm2 -sysc=opt_if -cflags "-D__STDC_FORMAT_MACROS -DNVDLA_REFERENCE_MODEL_ENABLE -DUVMC_MAX_WORDS=2048 -DVCS -I/home/ubuntu1604/nvdla_proj/hw/third_party_tools/uvmc-2.3.0/src/connect/sc -I/home/ubuntu1604/synopsys/vcs_2019.06-SP2/vcs/P-2019.06-SP2-12/include/systemc23 -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_scsv/sc -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_top_scsv_adapter/sc" -Mdir=csrc /home/ubuntu1604/nvdla_proj/hw/third_party_tools/uvmc-2.3.0/src/connect/sc/uvmc.cpp -l 'sysc.log' )
BUILD_SYSC::	/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player/csrc/sysc/uvmc.o
nvdla_dbb_scsv_extension_packer.o_DEP_O = /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player/csrc/sysc/nvdla_dbb_scsv_extension_packer.o
$(nvdla_dbb_scsv_extension_packer.o_DEP_O):	FORCE
	$(ACTIVE) $(MDIR_csrc) (cd /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player; $(VCS_HOME)/bin/syscan  -sysc=231 -V -work DEFAULT -full64 -cc /usr/bin/gcc -cpp /usr/bin/g++ -tlm2 -sysc=opt_if -cflags "-D__STDC_FORMAT_MACROS -DNVDLA_REFERENCE_MODEL_ENABLE -DUVMC_MAX_WORDS=2048 -DVCS -I/home/ubuntu1604/nvdla_proj/hw/third_party_tools/uvmc-2.3.0/src/connect/sc -I/home/ubuntu1604/synopsys/vcs_2019.06-SP2/vcs/P-2019.06-SP2-12/include/systemc231 -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_cmod_wrap/release/include -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_scsv/sc -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_top_scsv_adapter/sc" -Mdir=csrc /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_scsv/sc/nvdla_dbb_scsv_extension_packer.cpp -l 'sysc.log' )
BUILD_SYSC::	/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player/csrc/sysc/nvdla_dbb_scsv_extension_packer.o
nvdla_scsv_converter.o_DEP_O = /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player/csrc/sysc/nvdla_scsv_converter.o
$(nvdla_scsv_converter.o_DEP_O):	FORCE
	$(ACTIVE) $(MDIR_csrc) (cd /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player; $(VCS_HOME)/bin/syscan  -sysc=231 -V -work DEFAULT -full64 -cc /usr/bin/gcc -cpp /usr/bin/g++ -tlm2 -sysc=opt_if -cflags "-D__STDC_FORMAT_MACROS -DNVDLA_REFERENCE_MODEL_ENABLE -DUVMC_MAX_WORDS=2048 -DVCS -I/home/ubuntu1604/nvdla_proj/hw/third_party_tools/uvmc-2.3.0/src/connect/sc -I/home/ubuntu1604/synopsys/vcs_2019.06-SP2/vcs/P-2019.06-SP2-12/include/systemc231 -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_cmod_wrap/release/include -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_scsv/sc -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_top_scsv_adapter/sc" -Mdir=csrc /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_scsv/sc/nvdla_scsv_converter.cpp -l 'sysc.log' )
BUILD_SYSC::	/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player/csrc/sysc/nvdla_scsv_converter.o
nvdla_top_sc_layer.o_DEP_O = /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player/csrc/sysc/nvdla_top_sc_layer.o
$(nvdla_top_sc_layer.o_DEP_O):	FORCE
	$(ACTIVE) $(MDIR_csrc) (cd /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player; $(VCS_HOME)/bin/syscan  -sysc=231 -V -work DEFAULT -full64 -cc /usr/bin/gcc -cpp /usr/bin/g++ -tlm2 -sysc=opt_if -cflags "-D__STDC_FORMAT_MACROS -DNVDLA_REFERENCE_MODEL_ENABLE -DUVMC_MAX_WORDS=2048 -DVCS -I/home/ubuntu1604/nvdla_proj/hw/third_party_tools/uvmc-2.3.0/src/connect/sc -I/home/ubuntu1604/synopsys/vcs_2019.06-SP2/vcs/P-2019.06-SP2-12/include/systemc231 -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_cmod_wrap/release/include -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_scsv/sc -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_top_scsv_adapter/sc" -Mdir=csrc /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_top_scsv_adapter/sc/nvdla_top_sc_layer.cpp -l 'sysc.log' )
BUILD_SYSC::	/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player/csrc/sysc/nvdla_top_sc_layer.o
log.o_DEP_O = /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player/csrc/sysc/log.o
$(log.o_DEP_O):	FORCE
	$(ACTIVE) $(MDIR_csrc) (cd /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player; $(VCS_HOME)/bin/syscan  -sysc=231 -V -work DEFAULT -full64 -cc /usr/bin/gcc -cpp /usr/bin/g++ -tlm2 -sysc=opt_if -cflags "-D__STDC_FORMAT_MACROS -DNVDLA_REFERENCE_MODEL_ENABLE -DUVMC_MAX_WORDS=2048 -DVCS -I/home/ubuntu1604/nvdla_proj/hw/third_party_tools/uvmc-2.3.0/src/connect/sc -I/home/ubuntu1604/synopsys/vcs_2019.06-SP2/vcs/P-2019.06-SP2-12/include/systemc231 -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_cmod_wrap/release/include -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_scsv/sc -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_top_scsv_adapter/sc" -Mdir=csrc /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_top_scsv_adapter/sc/log.cpp -l 'sysc.log' )
BUILD_SYSC::	/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player/csrc/sysc/log.o
nvdla_top_sc_adapter_DEP_O = /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player/csrc/sysc/nvdla_top_sc_adapter/nvdla_top_sc_adapter.o
$(nvdla_top_sc_adapter_DEP_O):	FORCE
	$(ACTIVE) $(MDIR_csrc) (cd /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player; $(VCS_HOME)/bin/syscan  -sysc=231 -V -work DEFAULT -full64 -cc /usr/bin/gcc -cpp /usr/bin/g++ -tlm2 -sysc=opt_if -cflags "-D__STDC_FORMAT_MACROS -DNVDLA_REFERENCE_MODEL_ENABLE -DUVMC_MAX_WORDS=2048 -DVCS -I/home/ubuntu1604/nvdla_proj/hw/third_party_tools/uvmc-2.3.0/src/connect/sc -I/home/ubuntu1604/synopsys/vcs_2019.06-SP2/vcs/P-2019.06-SP2-12/include/systemc231 -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_cmod_wrap/release/include -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_scsv/sc -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_top_scsv_adapter/sc" -Mdir=csrc /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_top_scsv_adapter/sc/nvdla_top_sc_adapter.cpp:nvdla_top_sc_adapter -l 'sysc.log' )
BUILD_SYSC::	/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player/csrc/sysc/nvdla_top_sc_adapter/nvdla_top_sc_adapter.o
rm_convertor_dpi.o_DEP_O = /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player/csrc/sysc/rm_convertor_dpi.o
$(rm_convertor_dpi.o_DEP_O):	FORCE
	$(ACTIVE) $(MDIR_csrc) (cd /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player; $(VCS_HOME)/bin/syscan  -full64 -sysc=231 -cpp /usr/bin/g++ -Mdir=csrc -cflags "-Icsrc/sysc/include" -cflags "-I/home/ubuntu1604/nvdla_proj/hw/cmod/include -I/home/ubuntu1604/nvdla_proj/hw/cmod/include/nvdla_ness_header -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/spec/defs" -cflags "-pipe -DVCSMX -DUVM_DPI_DO_TYPE_CHECK" /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/rm_nvdla_top/rm_convertor_dpi.cpp  )
BUILD_SYSC::	/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player/csrc/sysc/rm_convertor_dpi.o
