SYSC_MODULE = rm_convertor_dpi
V = @
CXX = /usr/bin/g++
CXXFLAGS =  -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player/csrc/sysc/include -I/home/ubuntu1604/nvdla_proj/hw/cmod/include -I/home/ubuntu1604/nvdla_proj/hw/cmod/include/nvdla_ness_header -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/spec/defs -pipe -DVCSMX -DUVM_DPI_DO_TYPE_CHECK -DVCSSYSTEMC=1  -MMD -m64 -fPIC
INCLUDES = \
	-I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/rm_nvdla_top \
	-I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player/csrc/sysc/include \
	-I/home/ubuntu1604/synopsys/vcs_2019.06-SP2/vcs/P-2019.06-SP2-12/include/systemc231 \
	-I/home/ubuntu1604/synopsys/vcs_2019.06-SP2/vcs/P-2019.06-SP2-12/include/systemc231 \
	-Iinclude \
	-I$(VCS_HOME)/lib \
	-I$(VCS_HOME)/include \
	-I$(VCS_HOME)/include/cosim/bf \
	-I$(SNPS_SIM_OVRD)/include \
	-I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player

OBJS = rm_convertor_dpi.o

module-rm_convertor_dpi:	$(OBJS)
rm_convertor_dpi.o:
	@rm -f rm_convertor_dpi.o
	@$(MAKE) -f Makefile_shared clean
	$(V) $(CXX) $(INCLUDES) $(CXXFLAGS) -c /home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/rm_nvdla_top/rm_convertor_dpi.cpp -o $@ 

clean:
	$(V) rm -f rm_convertor_dpi.o

-include rm_convertor_dpi.d

