SYSC_MODULE = uvmc
V = @
CXX = /usr/bin/g++
CXXFLAGS =  -D__STDC_FORMAT_MACROS -DNVDLA_REFERENCE_MODEL_ENABLE -DUVMC_MAX_WORDS=2048 -DVCS -I/home/ubuntu1604/nvdla_proj/hw/third_party_tools/uvmc-2.3.0/src/connect/sc -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_scsv/sc -I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/vip/reference_model/nvdla_top_scsv_adapter/sc -DVCSSYSTEMC=1  -MMD -m64 -fPIC
INCLUDES = \
	-I/home/ubuntu1604/nvdla_proj/hw/third_party_tools/uvmc-2.3.0/src/connect/sc \
	-I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player/csrc/sysc/include \
	-I/home/ubuntu1604/synopsys/vcs_2019.06-SP2/vcs/P-2019.06-SP2-12/include/systemc231 \
	-I/home/ubuntu1604/synopsys/vcs_2019.06-SP2/vcs/P-2019.06-SP2-12/include/systemc231 \
	-I/home/ubuntu1604/synopsys/vcs_2019.06-SP2/vcs/P-2019.06-SP2-12/include/systemc231/include/tlm \
	-I/home/ubuntu1604/synopsys/vcs_2019.06-SP2/vcs/P-2019.06-SP2-12/etc/systemc/tlm/tli \
	-I/home/ubuntu1604/synopsys/vcs_2019.06-SP2/vcs/P-2019.06-SP2-12/include/systemc231/examples/tlm/common/include \
	-Iinclude \
	-I$(VCS_HOME)/lib \
	-I$(VCS_HOME)/include \
	-I$(VCS_HOME)/include/cosim/bf \
	-I$(SNPS_SIM_OVRD)/include \
	-I/home/ubuntu1604/nvdla_proj/hw/outdir/nv_small/verif/testbench/trace_player

OBJS = uvmc.o

module-uvmc:	$(OBJS)
uvmc.o:
	@echo "Compiling /home/ubuntu1604/nvdla_proj/hw/third_party_tools/uvmc-2.3.0/src/connect/sc/uvmc.cpp"
	@rm -f uvmc.o
	@$(MAKE) -f Makefile_shared clean
	$(V) $(CXX) $(INCLUDES) $(CXXFLAGS) -c /home/ubuntu1604/nvdla_proj/hw/third_party_tools/uvmc-2.3.0/src/connect/sc/uvmc.cpp -o $@ 

clean:
	$(V) rm -f uvmc.o

-include uvmc.d

